# format = """
# $username \
# $hostname \
# $directory \
# $git_branch \
# $git_status \
# $fill \
# $c \
# $elixir \
# $elm \
# $golang \
# $haskell \
# $java \
# $julia \
# $nodejs \
# $nim \
# $scala \
# $rust \
# $python \
# $conda \
# $time\n  \
# [󱞪 ](fg:iris)
# """
format = """
[](fg:gold)\
$username[](bg:gold fg:iris)\
$hostname\
$directory \
$git_branch\
$git_status \
$fill \
$c $rust $deno $conda $python\
\n \
[󱞪 ](fg:foam)
"""

palette = "everforest"

[palettes.everforest]
bg_dim = "#232a2e"
bg0 = "#2d353b"
bg1 = "#343f44"
bg2 = "#3d484d"
bg3 = "#475258"
bg4 = "#4f585e"
bg5 = "#56635f"
bg_visual = "#543a48"
bg_red = "#514045"
bg_green = "#425047"
bg_blue = "#3a515d"
bg_yellow = "#4d4c43"

fg = "#d3c6aa"
red = "#e67e80"

orange = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
aqua = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"
grey0 = "#7a8478"
grey1 = "#859289"
grey2 = "#9da9a0"
statusline1 = "#a7c080"
statusline2 = "#d3c6aa"
statusline3 = "#e67e80"

overlay = "#2e383c"
love = "#e67e80"
gold = "#dbbc7f"
rose = "#e67e80"
pine = "#7fbbb3"
foam = "#83c092"
iris = "#d699b6"




# [palettes.rose-pine]
# overlay = '#26233a'
# love = '#eb6f92'
# gold = '#f6c177'
# rose = '#ebbcba'
# pine = '#31748f'
# foam = '#9ccfd8'
# iris = '#c4a7e7'

[directory]
format = "[](fg:iris bg:love)[ $path ]($style)[](fg:love)"
style = "bg:love fg:overlay"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)"
style = "bg:overlay fg:foam"
symbol = ""

[git_status]
disabled = false
style = "bg:overlay fg:love"
format = '([ $all_status$ahead_behind]($style))[](fg:overlay)'
up_to_date = '[ ✓ ](bg:overlay fg:iris)'
untracked = '[?\($count\)](bg:overlay fg:gold)'
stashed = '[$](bg:overlay fg:iris)'
modified = '[!\($count\)](bg:overlay fg:gold)'
renamed = '[»\($count\)](bg:overlay fg:iris)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:overlay fg:gold)'
ahead = '[⇡\(${count}\)](bg:overlay fg:foam)'
diverged = '⇕[\[](bg:overlay fg:iris)[⇡\(${ahead_count}\)](bg:overlay fg:foam)[⇣\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
behind = '[⇣\(${count}\)](bg:overlay fg:rose)'

[time]
disabled = false
format = "[](fg:overlay)[ $time 󰴈 ]($style)[](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%I:%M%P"
use_12hr = true

[hostname]
disabled = false
format = "[ 󰣇 $hostname ]($style)"
ssh_only = false
style = "bg:iris fg:overlay"

[username]
disabled = false
format = "[ 󰧱 $user ]($style)"
show_always = true
style_root = "bg:gold fg:overlay"
style_user = "bg:gold fg:overlay"

# Languages

[c]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[elixir]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[elm]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[golang]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[haskell]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[java]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[julia]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:overlay fg:foam"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = ""

[scala]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[python]
style = "bg:overlay fg:foam"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = ' '

[conda]
style = "bg:overlay fg:foam"
format = "[](fg:overlay)[$symbol$environment]($style)[](fg:overlay) "
symbol = '  '
ignore_base = false

[deno]
style = "bg:overlay fg:foam"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
symbol = ' '


